### ISSUE TITLE
feature request: ability to create new engines as plugins

### ISSUE THREAD

**Issue by tomgco** [shoreditch-ops/minigun#32]
I am looking at creating a RabbitMQ engine for Minigun. At the moment I am finding myself having to fork minigun-core to add what I need, do you plan to implement support for creating engines outside of minigun-core?

**Comment by tomgco** [comment]
Just going to note down an example interface to follow. I will also point out some things which I think could be abstracted away as they seem to be repeated in every engine (for now).

```js
module.exports = function (config, ee) {
  compile: (scenarioSpec, tasks) => {
  },
  createStep: (requestSpec) => {
    return function f(context, callback) {
      //implementation handles when it ends and firing of event emitters
      context.ws.send(requestSpec.send, err => callback(err));
    }
  }
}
```

Thoughts are an engine exposes the createStep function, this will be called internally by mapping the scenarioSpec, the compile export will be the same as it currently is.

**Comment by hassy** [comment]
This is awesome :+1: 

I think engines for common protocols should be bundled with Minigun for better developer experience. If someone were to write an engine for a custom protocol and didn't want to distribute it, they'd have to maintain a private fork (which would be easy to keep up to date since the change would be isolated to one file).

The two bundled engines already sort-of specify an interface, but as you say it should be cleaned up and documented. :+1: (Writing an AMQP engine will be a great help for this as the semantics of the protocol are quite different from HTTP or WS and so the existing interface may need to be tweaked.)

Looking forward to the PRs :dancer:
